### ISSUE TITLE
Error after updating unique aliases

### ISSUE THREAD

**Issue by rreichen** [dmitryd/typo3-realurl#136]
After updating an unique alias of realurl on a page n (n>1) the list of page 1 will appear again. Return back to page n the following error message then accurs:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1298012500: Required argument "uid" is not set for DmitryDulepov\Realurl\Controller\AliasesController->edit. | TYPO3\CMS\Extbase\Mvc\Controller\Exception\RequiredArgumentMissingException thrown in file /srv/www/vhosts/typo3_7605/typo3/sysext/extbase/Classes/Mvc/Controller/AbstractController.php in line 430. Requested URL: http://10.50.15.14/typo3/index.php?M=web_RealurlRealurl&moduleToken=c6cc00fffd89f8fdbcefca99d2b3adb819b93160&id=1&tx_realurl_web_realurlrealurl%5Baction%5D=edit&tx_realurl_web_realurlrealurl%5Bcontroller%5D=Aliases&tx_realurl_web_realurlrealurl%5BselectedAlias%5D=tt_news&tx_realurl_web_realurlrealurl%5B%40widget_0%5D%5BcurrentPage%5D=69

My Versions are:
TYPO3: 7.6.5
realurl: 2.0.11

**Comment by rreichen** [comment]
Now I have upgraded realurl to Version 2.0.14 but the explained error still accures.

**Comment by dmitryd** [comment]
Do you see a message that it is fixed in 2.0.14?

**Comment by rreichen** [comment]
No I don’t see anyone. First I thought that the files “Configuration/TCA/tx_realurl….php” or “Classes/Controller/..php” could be an I changed them all but the described error still appears.

Von: Dmitry Dulepov [mailto:notifications@github.com]
Gesendet: Dienstag, 19. April 2016 10:02
An: dmitryd/typo3-realurl
Cc: Reichenauer, Roland
Betreff: Re: [dmitryd/typo3-realurl] Error after updating unique aliases (#136)


Do you see a message that it is fixed in 2.0.14?

**Comment by rreichen** [comment]
The described problem is still present and I get no response concerning to any activities for solving it. A solution of that problem is necessary for a productiv operation with realurl and tt_news. I'm not a TYPO3 developer and so I'm dependent on help. 
 My Versions are:  
TYPO3: 7.6.5
realurl: 2.0.14
tt_news: 7.6.1
php: 5.5.14

**Comment by rreichen** [comment]
By updating an unique alias and afterwards apdating the list the same error message accurs. There must be so many aliases that one page exceeds.

**Comment by dmitryd** [comment]
This is a free project and development happens when there is free time. Currently I have no free time.

**Comment by rreichen** [comment]
Sorry; this shall not be a demand. It is only a petition for help!

**Comment by rreichen** [comment]
Updating an unique alias of realurl on a page n (n>1) the list of page 1 will appear again. Return back to page n everything works fine.
Deleting an unique alias and trying to navigate to an other page of the list the old error message appears with:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1298012500: Required argument "uid" is not set for DmitryDulepov\Realurl\Controller\AliasesController->delete. | TYPO3\CMS\Extbase\Mvc\Controller\Exception\RequiredArgumentMissingException thrown in file /srv/www/vhosts/typo3_7609/typo3/sysext/extbase/Classes/Mvc/Controller/AbstractController.php in line 430. Requested URL: http://10.50.15.14/typo3/index.php?M=web_RealurlRealurl&moduleToken=378141078a3ca5dba0a1299a3020bff37b39ce53&id=4&tx_realurl_web_realurlrealurl%5Baction%5D=delete&tx_realurl_web_realurlrealurl%5Bcontroller%5D=Aliases&tx_realurl_web_realurlrealurl%5BselectedAlias%5D=tt_news&tx_realurl_web_realurlrealurl%5B%40widget_0%5D%5BcurrentPage%5D=71 
So opened the issue again.

**Comment by rreichen** [comment]
I'm not able to reopen this issue. So I created a new with number #178. So it still remains closed. Sorry!
