### ISSUE TITLE
Error after deleting unique aliases

### ISSUE THREAD

**Issue by rreichen** [dmitryd/typo3-realurl#178]
Updating an unique alias of realurl on a page n (n>1) the list of page 1 will appear again. Return back to page n everything works fine.
Deleting an unique alias and trying to navigate to an other page of the list the old error message appears with:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1298012500: Required argument "uid" is not set for DmitryDulepov\Realurl\Controller\AliasesController->delete. | TYPO3\CMS\Extbase\Mvc\Controller\Exception\RequiredArgumentMissingException thrown in file /srv/www/vhosts/typo3_7609/typo3/sysext/extbase/Classes/Mvc/Controller/AbstractController.php in line 430. Requested URL: http://10.50.15.14/typo3/index.php?M=web_RealurlRealurl&moduleToken=378141078a3ca5dba0a1299a3020bff37b39ce53&id=4&tx_realurl_web_realurlrealurl%5Baction%5D=delete&tx_realurl_web_realurlrealurl%5Bcontroller%5D=Aliases&tx_realurl_web_realurlrealurl%5BselectedAlias%5D=tt_news&tx_realurl_web_realurlrealurl%5B%40widget_0%5D%5BcurrentPage%5D=71

**Comment by dmitryd** [comment]
And why did you create this new issue? This is fixed in the development version and not yet released anywhere.

2.0.14 was out on April 18th: https://github.com/dmitryd/typo3-realurl/tree/2.0.14
#136 was fixed on May 6.

Isn't it clear that this is not yet released to TER?

Some time lost uselessly...

**Comment by rreichen** [comment]
In #136 the wrong behavour referring to updating aliases was described and fixed on May, 6th. I now this. But there is an other wrong behavour referring to deleting aliases which is still present. I detected it after testing the fixed development version and described it in #178. I hope comprehensibly. Sorry, if not!

**Comment by dmitryd** [comment]
I will check if I can reproduce it.
